version: "3"

services:

  web:
    image: "go_microservices"
    build: .
#    volumes:
#      - ./src:/src
    environment: 
      WAIT_HOSTS: nats:4222
      NATS_URL: nats://nats:4222
#      GIN_MODE: release
    ports:
      - "8080:8080"

#  db:
#    image: "postgres:9-alpine"
    #hostname: postgres
#    ports:
#      - "5432:5432"

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
