version: "3"

services:

  web:
    image: "go_microservices"
    build: .
#    volumes:
#      - ./src:/src
#    environment: 
#      WAIT_HOSTS: db:5432
#      GIN_MODE: release
    ports:
      - "8000:8000"

#  db:
#    image: "postgres:9-alpine"
    #hostname: postgres
#    ports:
#      - "5432:5432"
